# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db90fdf44a23c4fdca695e8ca8872a9e07196dde1bf700bb7460fb80091942801cd0adf981843e9a16ec36f583b28a56a5e616fe4d9dc216f6e6b47789e32d06

test:
  secret_key_base: 8cd2f582b5491658347a32be96611cc3cdff88c21e6cf7687f5087c0e3b3408c2094aa1db02b949b86e1ae143fc9d05bc249ac674cc0fd9cfed7446a4a85d918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8cd2f582b5491658347a32be96611cc3cdff88c21e6cf7687f5087c0e3b3408c2094aa1db02b949b86e1ae143fc9d05bc249ac674cc0fd9cfed7446a4a85d918
